config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :customers, only: [:index, :show, :update]
  end
  namespace :admin do
    resources :reviews, only: [:index, :show, :destroy]
  end

  root to: 'public/homes#top'

  scope module: :public do
    resources :reviews, only: [:index, :new, :create, :show, :update, :destroy] do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
  end

devise_for :admins, controllers: {
  sessions:      'admin/admins/sessions',
  passwords:     'admin/admins/passwords',
  registrations: 'admin/admins/registrations'
}
devise_for :customers, controllers: {
  sessions:      'public/customers/sessions',
  passwords:     'public/customers/customers/passwords',
  registrations: 'public/customers/registrations'
}
devise_scope :customer do
  post 'customers/guest_sign_in', to: 'public/customers/sessions#guest_sign_in'
end

  scope module: :public do
    get "customers/mypage" => "customers#show", as: "customer"
    resources :customers do
      member do
        get :favorites
      end
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :review
  belongs_to :customer

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reviews, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |customer|
      customer.name = "ゲスト"
      customer.password = SecureRandom.urlsafe_base64
    end
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :customer
  belongs_to :review
end

app/models/fovorite.rb
class Fovorite < ApplicationRecord
  belongs_to :customer
  belongs_to :review
end

app/models/game_genre.rb
class GameGenre < ApplicationRecord
 has_many :review_genre_intermediates, dependent: :destroy
 has_many :reviews, through: :review_genre_intermediates
end

app/models/review.rb
class Review < ApplicationRecord
  has_many :review_genre_intermediates, dependent: :destroy
  has_many :game_genres, through: :review_genre_intermediates
  belongs_to :customer
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :game_title, presence: true
  validates :evaluation, presence: true
  validates :review_title, presence: true
  validates :review, presence: true

  validates :evaluation, numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 1
  }, presence: true

  scope :published, -> {where(status: true)}
  scope :unpublished, -> {where(status: false)}

  def favorited_by?(customer)
    favorites.where(customer_id: customer.id).exists?
  end
end

app/models/review_genre_intermediate.rb
class ReviewGenreIntermediate < ApplicationRecord
  belongs_to :review
  belongs_to :game_genre
end

app/controllers/admin/admins/passwords_controller.rb
# frozen_string_literal: true

class Admin::Admins::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admin/admins/sessions_controller.rb
# frozen_string_literal: true

class Admin::Admins::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/admins/unlocks_controller.rb
# frozen_string_literal: true

class Admin::Admins::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :move_to_signed_in

  def index
    @customers = Customer.all.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
    @reviews = @customer.reviews.order(id: "DESC").page(params[:page])
  end

  def update
    customer = Customer.find(params[:id])
    customer.update(customer_params)
    redirect_to admin_customer_path
  end

  private

  def customer_params
    params.require(:customer).permit(:name, :email, :encrypted_password, :is_valid)
  end

  def move_to_signed_in
    unless admin_signed_in?
      redirect_to  '/admins/sign_in'
    end
  end
end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < ApplicationController
  before_action :move_to_signed_in

  def index
    @reviews = params[:tag_id].present? ? GameGenre.find(params[:tag_id]).reviews.order(id: "DESC").page(params[:page]) : Review.all.order(id: "DESC").page(params[:page])
  end

  def destroy
    Review.find(params[:id]).destroy
    redirect_to request.referer
  end

  def show
     @review = Review.find(params[:id])
  end

  private
  def move_to_signed_in
    unless admin_signed_in?
      redirect_to  '/admins/sign_in'
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?


  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end


  private

  def after_sign_in_path_for(resource_or_scope)
    if resource_or_scope.is_a?(Admin)
        admin_reviews_path
    else
        reviews_path
    end
  end

  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :customer
        root_path
    elsif resource_or_scope == :admin
        admin_session_path
    else
        root_path
    end
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customer/customers_helper.rb
module Customer::CustomersHelper
end

app/helpers/customer/fovorites_helper.rb
module Customer::FovoritesHelper
end

app/helpers/customer/review_comment_helper.rb
module Customer::ReviewCommentHelper
end

app/helpers/customer/reviews_helper.rb
module Customer::ReviewsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/reviews/index.html.erb
<div class="container my-3">

  <div class="row">
    <h1 class="bg-secondary p-2 text-white rounded-pill">レビュー</h1>
  </div>

  <%= form_tag reviews_path, method: :get, class: 'boards__searchForm' do %>
      <%= select_tag :tag_id,
                     options_from_collection_for_select(GameGenre.all, :id, :genre_name, params[:tag_id]),
                     {
                       prompt: 'タグで絞り込み検索',
                       onchange: 'submit(this.form);'
                     }
      %>
  <% end %>


  <div class="row">
    <% @reviews.each do |review| %>
　　<div class="col-5 p-3 mx-4 my-2 border border-info border-5">

　　  <div class="d-flex">
        <div>
          <p>投稿者: <%= review.customer.name %>[<%= review.created_at.strftime('%Y/%m/%d %H:%M') %>]</p>
        </div>

        <div class="ml-auto">
          ♡<%= review.favorites.count %><br>
          <%= link_to "削除", admin_review_path(review), method: :delete, "data-confirm" => "本当に削除しますか？", class: "text-danger" %>
        </div>
      </div>

      <div class="font-weight-bold h5">
        <u>ゲームタイトル</u>
        <%= link_to admin_review_path(review.id) do %>
          <p class="ml-3 mt-2"><%= review.game_title %></p>
        <% end %>
      </div>

      <div class="py-2 font-weight-bold h5">
        <u>評価</u><br>
        <div class="detail-value ml-3 mt-2", id="star-comf-<%= review.id %>"></div>
          <script>
            $('#star-comf-<%= review.id %>').raty({
              size: 38,
              starOff:  '<%= asset_path('star-off.png') %>',
              starOn : '<%= asset_path('star-on.png') %>',
              starHalf: '<%= asset_path('star-half.png') %>',
              half: true,
              readOnly: true,
              score: <%= review.evaluation %>,
            });
          </script>
      </div>

      <div class="py-2 text-break  text-wrap">
        <div class="font-weight-bold h5">
          <u>レビュー</u>
        </div>
        <div class="ml-3 font-weight-bold h5">
          <%= review.review_title %>
        </div>
        <span ><%= review.review %></span><br>
      </div>

      <div class="py-2 font-weight-bold h5">
        <u>ジャンル</u><br>
        <% review.game_genres.each do |genre| %>
          <p class="ml-3 mt-2"><%= genre.genre_name %></p>
        <% end %>
      </div>
    </div>

    <% end %>
  </div>

  <div class="row">
    <div class="mx-auto"><%= paginate @reviews %></div>
  </div>


</div>

app/views/admin/reviews/show.html.erb
<div class="container my-3">
  <div class="row">
    <h1 class="bg-secondary p-2 text-white rounded-pill">レビュー詳細</h1>
  </div>

  <div>
    <p>投稿者: <%= @review.customer.name %>[<%= @review.created_at.strftime('%Y/%m/%d %H:%M') %>]</p>

    <div class="font-weight-bold h5">
        <u>ゲームタイトル</u>
        <p class="ml-3 mt-2"><%= @review.game_title %></p>
      </div>

      <div class="py-2 font-weight-bold h5">
        <u>評価</u><br>
        <div class="detail-value ml-3 mt-2", id="star-comf-<%= @review.id %>"></div>
          <script>
            $('#star-comf-<%= @review.id %>').raty({
              size: 38,
              starOff:  '<%= asset_path('star-off.png') %>',
              starOn : '<%= asset_path('star-on.png') %>',
              starHalf: '<%= asset_path('star-half.png') %>',
              half: true,
              readOnly: true,
              score: <%= @review.evaluation %>,
            });
          </script>
      </div>

      <div class="py-2 text-break  text-wrap">
        <div class="font-weight-bold h5">
          <u>レビュー</u>
        </div>
        <div class="ml-3 font-weight-bold h5">
          <%= @review.review_title %>
        </div>
        <span ><%= @review.review %></span><br>
      </div>

      <div class="py-2 font-weight-bold h5">
        <u>ジャンル</u><br>
        <% @review.game_genres.each do |genre| %>
          <p class="ml-3 mt-2"><%= genre.genre_name %></p>
        <% end %>
      </div>
    </div>


     <div class="mt-5">
       <u><h5 class="font-weight-bold">コメント</h5></u><br>

      <div class="mt-2 text-break  text-wrap">
        <% @review.comments.each do |comment| %>
          <div class="mb-3 border">
            <div class="bg-secondary p-1 text-white d-inline-block"><%= comment.customer.name %>[<%= comment.created_at.strftime('%Y/%m/%d %H:%M') %>]</div>
            <div><%= comment.comment %></div>
            <%= link_to "削除", review_comment_path(comment.review, comment), method: :delete, class: "text-danger" %><br>
          </div>
        <% end %>
      </div>

    </div>

  </div>
</div>