config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :customers, only: [:index, :show, :update]
  end
  namespace :admin do
    resources :reviews, only: [:index, :show, :destroy]
  end

  root to: 'public/homes#top'

  scope module: :public do
    resources :reviews, only: [:index, :new, :create, :show, :update, :destroy] do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
  end

devise_for :admins, controllers: {
  sessions:      'admin/admins/sessions',
  passwords:     'admin/admins/passwords',
  registrations: 'admin/admins/registrations'
}
devise_for :customers, controllers: {
  sessions:      'public/customers/sessions',
  passwords:     'public/customers/customers/passwords',
  registrations: 'public/customers/registrations'
}
devise_scope :customer do
  post 'customers/guest_sign_in', to: 'public/customers/sessions#guest_sign_in'
end

  scope module: :public do
    get "customers/mypage" => "customers#show", as: "customer"
    resources :customers do
      member do
        get :favorites
      end
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :review
  belongs_to :customer

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reviews, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |customer|
      customer.name = "ゲスト"
      customer.password = SecureRandom.urlsafe_base64
    end
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :customer
  belongs_to :review
end

app/models/fovorite.rb
class Fovorite < ApplicationRecord
  belongs_to :customer
  belongs_to :review
end

app/models/game_genre.rb
class GameGenre < ApplicationRecord
 has_many :review_genre_intermediates, dependent: :destroy
 has_many :reviews, through: :review_genre_intermediates
end

app/models/review.rb
class Review < ApplicationRecord
  has_many :review_genre_intermediates, dependent: :destroy
  has_many :game_genres, through: :review_genre_intermediates
  belongs_to :customer
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :game_title, presence: true
  validates :evaluation, presence: true
  validates :review_title, presence: true
  validates :review, presence: true

  validates :evaluation, numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 1
  }, presence: true

  scope :published, -> {where(status: true)}
  scope :unpublished, -> {where(status: false)}

  def favorited_by?(customer)
    favorites.where(customer_id: customer.id).exists?
  end
end

app/models/review_genre_intermediate.rb
class ReviewGenreIntermediate < ApplicationRecord
  belongs_to :review
  belongs_to :game_genre
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :move_to_signed_in

  def index
    @customers = Customer.all.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
    @reviews = @customer.reviews.order(id: "DESC").page(params[:page])
  end

  def update
    customer = Customer.find(params[:id])
    customer.update(customer_params)
    redirect_to admin_customer_path
  end

  private

  def customer_params
    params.require(:customer).permit(:name, :email, :encrypted_password, :is_valid)
  end

  def move_to_signed_in
    unless admin_signed_in?
      redirect_to  '/admins/sign_in'
    end
  end
end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < ApplicationController
  before_action :move_to_signed_in

  def index
    @reviews = params[:tag_id].present? ? GameGenre.find(params[:tag_id]).reviews.order(id: "DESC").page(params[:page]) : Review.all.order(id: "DESC").page(params[:page])
  end

  def destroy
    Review.find(params[:id]).destroy
    redirect_to request.referer
  end

  def show
     @review = Review.find(params[:id])
  end

  private
  def move_to_signed_in
    unless admin_signed_in?
      redirect_to  '/admins/sign_in'
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?


  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end


  private

  def after_sign_in_path_for(resource_or_scope)
    if resource_or_scope.is_a?(Admin)
        admin_reviews_path
    else
        reviews_path
    end
  end

  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :customer
        root_path
    elsif resource_or_scope == :admin
        admin_session_path
    else
        root_path
    end
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customer/customers_helper.rb
module Customer::CustomersHelper
end

app/helpers/customer/fovorites_helper.rb
module Customer::FovoritesHelper
end

app/helpers/customer/review_comment_helper.rb
module Customer::ReviewCommentHelper
end

app/helpers/customer/reviews_helper.rb
module Customer::ReviewsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <% link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GameThoughts</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-expand-lg border-bottom border-4 border-dark py-4 bg-success">
      <%= link_to root_path do %>
          <h1 class="text-dark border border-dark  py-1 px-4 bg-white">GAME</h1>
        <% end %>

        <ul class="navbar-nav ml-auto">
          <% if customer_signed_in? %>
            <li>
              <%= link_to customer_path do %>
                <div class="text-white font-weight-bold mr-4">Myレビュー</div>
              <% end %>
            </li>
            <li>
              <%= link_to reviews_path do %>
                <div class="text-white font-weight-bold mr-4">レビュー一覧</div>
              <% end %>
            </li>
            <li>
              <%= link_to favorites_customer_path(current_customer.id) do %>
                <div class="text-white font-weight-bold mr-4">いいね一覧</div>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_customer_session_path, method: :delete do %>
                <div class="text-white font-weight-bold mr-4">ログアウト</div>
              <% end %>
            </li>
          <% elsif admin_signed_in? %>
            <li>
              <%= link_to admin_reviews_path do %>
                <div class="text-white font-weight-bold mr-4">レビュー一覧</div>
              <% end %>
            </li>
            <li>
              <%= link_to admin_customers_path do %>
                <div class="text-white font-weight-bold mr-4">ユーザー一覧</div>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_admin_session_path, method: :delete do %>
                <div class="text-white font-weight-bold mr-4">ログアウト</div>
              <% end %>
            </li>
          <% else %>
            <li>
              <%= link_to reviews_path do %>
                <div class="text-white font-weight-bold mr-4">レビュー一覧</div>
              <% end %>
            </li>
            <li>
              <%= link_to customers_guest_sign_in_path, method: :post do %>
                <div class="text-white font-weight-bold mr-4">ゲストログイン</div>
              <% end %>
            </li>
            <li>
              <%= link_to new_customer_registration_path do %>
                <div class="text-white font-weight-bold mr-4">新規登録</div>
              <% end %>
            </li>
            <li>
              <%= link_to new_customer_session_path do %>
                <div class="text-white font-weight-bold mr-4">ログイン</div>
              <% end %>
            </li>
          <% end %>
        </ul>
    </header>
    <%= yield %>
    <footer class="row border-top border-dark border-4 p-5">
    </footer>
  </body>
</html>